### ISSUE TITLE
The AU print server connection check hangs

### ISSUE THREAD

**Issue by haselwarter** [Tyilo/auprint#4]
The AU print server connection check hangs. Tested today on eduroam. 

Temporary workaround: Commenting out `            and cls.check_smbclient_connection()`.

**Comment by BarrensZeppelin** [comment]
The problem is that
`smbclient -L 10.83.17.147`
requests a password interactively.

If you do
`smbclient -L 10.83.17.147 < /dev/null`
instead, you get
`Password for [WORKGROUP\zii]:session setup failed: NT_STATUS_NOT_SUPPORTED`
(or similar).

This is different to the error you get if you try to do the same from a non-authorized network.
I think we should just treat `NT_STATUS_NOT_SUPPORTED` as a success, just like `NT_STATUS_ACCESS_DENIED`.
